development:
  sessions:
    default:
      database: <%= ENV['MG_DB'] %>
      hosts: 
        - <%= ENV['MG_HOST_1'] %>
      username: <%= ENV['MG_USERNAME'] %>
      password: <%= ENV['MG_PASSWORD'] %>
    seaoo_scraper:
      database: <%= ENV['MG_DB_SC'] %>
      hosts: 
        - <%= ENV['MG_HOST_1_SC'] %>
      username: <%= ENV['MG_USERNAME_SC'] %>
      password: <%= ENV['MG_PASSWORD_SC'] %>

production:
  sessions:
    default:
      database: <%= ENV['MG_DB'] %>
      hosts: 
        - <%= ENV['MG_HOST_1'] %>
      username: <%= ENV['MG_USERNAME'] %>
      password: <%= ENV['MG_PASSWORD'] %>
    seaoo_scraper:
      database: <%= ENV['MG_DB_SC'] %>
      hosts: 
        - <%= ENV['MG_HOST_1_SC'] %>
      username: <%= ENV['MG_USERNAME_SC'] %>
      password: <%= ENV['MG_PASSWORD_SC'] %>