development:
  sessions:
    default:
      database: seaoo_web
      hosts: 
        - localhost:27017
    seaoo_scraper:
      database: seaoo
      hosts: 
        - ds041347.mongolab.com:41347
      username: ouvert
      password: Sch39YctLD7n

production:
  sessions:
    default:
      database: <%= ENV['MG_DB'] %>
      hosts: 
        - <%= ENV['MG_HOST_1'] %>
      username: <%= ENV['MG_USERNAME'] %>
      password: <%= ENV['MG_PASSWORD'] %>
    seaoo_scraper:
      database: <%= ENV['MG_DB_SC'] %>
      hosts: 
        - <%= ENV['MG_HOST_1_SC'] %>
      username: <%= ENV['MG_USERNAME_SC'] %>
      password: <%= ENV['MG_PASSWORD_SC'] %>